

# Combines the files generated by probedCells.py into a file for each 
# galID


galID_list = ['D9o2', 'D9q', 'D9m4a']
expn_list1 = ['0.900', '0.926', '0.950', '0.975', '0.990', '1.002']
expn_list2 = ['0.901', '0.925', '0.950', '0.976', '0.991', '1.001']
expn_list3 = ['0.900', '0.925', '0.950', '0.975', '0.990', '1.000']
expn_list = [expn_list1, expn_list2, expn_list3]
